ZAIUS-12634: Changed default vtsrc variable to empty array instead of null
ZaiusInc/zaius-magento-2 pull request #65
Opened 2020-09-01 23:48 UTC by tmollerus-zaius

This fixes an error that appeared in the logs for Golf Discount's Magento 2 connector, as per https://zaius-jira.atlassian.net/browse/ZAIUS-12634

2020-09-02 21:46 UTC, levilansing requested changes
> *[Reviewable](https://reviewable.io/reviews/zaiusinc/zaius-magento-2/65)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @cBrenDev, @levilansing, and @tmollerus-zaius)

___
*[Helper/Data.php, line 393 at r1](https://reviewable.io/reviews/zaiusinc/zaius-magento-2/65#-MGFm9QD4qbD29BXeSVl:-MGFkCNG3lvcla_8NBdZ:bq290dh) ([raw file](https://github.com/zaiusinc/zaius-magento-2/blob/a14fb9396097bc53447996e4f1f78ad137b2f2dd/Helper/Data.php#L393)):*
> ```PHP
> 
>     /**
>      * @return null|array
> ```

this is no longer accurate


<!-- Sent from Reviewable.io -->

2020-09-02 22:15 UTC, tmollerus-zaius reviewed
> *[Reviewable](https://reviewable.io/reviews/zaiusinc/zaius-magento-2/65)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @cBrenDev and @levilansing)

___
*[Helper/Data.php, line 393 at r1](https://reviewable.io/reviews/zaiusinc/zaius-magento-2/65#-MGFm9QD4qbD29BXeSVl:-MGFso8TD0qq7FEBRclS:b-l2tt7p) ([raw file](https://github.com/zaiusinc/zaius-magento-2/blob/a14fb9396097bc53447996e4f1f78ad137b2f2dd/Helper/Data.php#L393)):*
<details><summary><i>Previously, levilansing (Levi Lansing) wrote…</i></summary><blockquote>

this is no longer accurate
</blockquote></details>

Done, good catch.


<!-- Sent from Reviewable.io -->

2020-09-03 01:12 UTC, levilansing approved these changes
¯\\_(ツ)_/¯   <img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/zaiusinc/zaius-magento-2/65#-:-MGGWCby6yJqOEpryyqq:betf4th)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @cBrenDev)



<!-- Sent from Reviewable.io -->

2020-09-03 01:18 UTC, cBrenDev commented
LGTM as well. Wouldn't have caught Levi's point. Did search for things calling this function and none of those look to me like they'll have issues.





<!-- Sent from Reviewable.io -->

2020-09-03 01:19 UTC, cBrenDev approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/zaiusinc/zaius-magento-2/65#-:-MGGXumrEC_SXHsvwOpO:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2020-09-21 23:16 UTC, travish commented
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

Thanks @tmollerus-zaius & @levilansing for your contributions. LGTM.

@cbrendev , the current `master` branch has work in it that isn't in the QA site. The QA site is based on `branch-1.0.4`. I've gotten this work up there. I see no reason not to merge this into `master` if you're ready.





<!-- Sent from Reviewable.io -->

2020-09-22 14:54 UTC, merged